#! /bin/bash
_console ()
{
  local cur keywords
  
  COMPREPLY=()
  cur=${COMP_WORDS[COMP_CWORD]}
  keywords="$(echo "" | ./console | grep "^  " | cut -d\  -f2,3 | grep -v "\-\-" | grep -v "\[")"
  if [ $COMP_CWORD -eq 2 ]; then
		return 0
  else
    COMPREPLY=( $(compgen -W "$keywords" -- $cur ) )
  fi


  return 0
}
complete -F _console console
